apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-call-phone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auto-call-phone
  template:
    metadata:
      labels:
        app: auto-call-phone
    spec:
      containers:
        - name: auto-call-phone
          image: 192.168.31.103:80:5000/auto_call_phone:v1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: auto-call-phone-service
spec:
  selector:
    app: auto-call-phone
  ports:
      - port: 80
        targetPort: 8000
  type: LoadBalancer  # 修改为 NodePort，方便本地/局域网直接访问