definitions:
  viewmodels.PhoneStatus:
    properties:
      phone_number:
        type: integer
      remark:
        type: string
      status:
        type: integer
    type: object
  viewmodels.UploadPhoneExcelReq:
    properties:
      filePath:
        type: string
      userId:
        type: string
    type: object
  viewmodels.UploadPhoneExcelRsp:
    properties:
      effective_count:
        description: 有效数量
        type: integer
      int:
        description: 总共数量
        type: integer
      list:
        items:
          $ref: '#/definitions/viewmodels.PhoneStatus'
        type: array
      repeat:
        type: integer
    type: object
info:
  contact: {}
paths:
  /update:
    put:
      consumes:
      - application/json
      description: update
      parameters:
      - description: 用户更新后信息
        in: body
        name: Object
        required: true
        schema:
          $ref: '#/definitions/viewmodels.UploadPhoneExcelReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/viewmodels.UploadPhoneExcelRsp'
      summary: 更新用户信息
      tags:
      - 测试4
swagger: "2.0"
